### ISSUE TITLE
New on Kinesis

### ISSUE THREAD

**Issue by emajus** [awslabs/amazon-kinesis-client-net#12]
Hi everyone, i'm really new with all this AWS technologies.

I need a kinesis consumer for a stream with 10 shards, validate the data and write it to s3 buckets .

I would like if anyone can help me with the KCL implementation in my project, a guided tutorial or something. 

It is always mandatory to have the kcl.properties, the AWS Credentials in enviroment variables, run the bootstrap.exe, etc? 

Thank you all

**Comment by emajus** [comment]
I'm having this error when trying to run the consumer.

![captura](https://cloud.githubusercontent.com/assets/11321067/23075974/27bea434-f504-11e6-9572-7d9ecb5f7db9.JPG)

**Comment by pfifer** [comment]
GitHub is primarily for issues with the library itself, for questions about Kinesis it's better to post on the [Kinesis AWS Forum](https://forums.aws.amazon.com/forum.jspa?forumID=169).  For sending data to S3 it might be easier to consider [Kinesis Firehose](https://aws.amazon.com/kinesis/firehose/).  If Firehose doesn't work for you you might want to consider the [Kinesis Connectors](https://github.com/awslabs/amazon-kinesis-connectors).

The error you posted appears to be an issue with finding the jars for the Kinesis Client Library.  It could be caused by the Jars not being downloaded to the correct location.
